ALTER TABLE submissions ADD COLUMN IF NOT EXISTS volume INTEGER;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS issue_number INTEGER;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS publish_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS published_html TEXT;
